# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-byte-order-marker
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.12.0
  hooks:
  - id: commitizen
    args: []
    exclude: ^(id_tests/data/.*|npm/node_modules/.*)
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: [-s, 'B404,B405,B506,B703,B308,B603']
    exclude: ^(id_tests/.*|npm/node_modules/.*|tools/.*|doc/.*|interdiode/static/vendor/.*)
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
  - id: shellcheck
    exclude: ^(id_tests/.*|npm/node_modules/.*|tools/.*|doc/.*)
- repo: https://github.com/d9pouces/mybestpractices
  rev: 0.3.4
  hooks:
  - id: mybestpractices-git-autotag
    args: [--only-branch, 'dev,master']
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
    exclude: ^(id_tests/data/.*|npm/node_modules/.*|interdiode/static/vendor/.*|interdiode/static/js/.*)
default_language_version:
  python: python3.9
