[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[project]
name = "hairgap"
version = "1.2.4"
description = "Basic protocol to send files using the hairgap binary ( github.com/cea-sec/hairgap )."
authors = [{ name = "Matthieu Gallet", email = "github@19pouces.net" }]
requires-python = ">=3.9,<4"
readme = "README.md"
license = "CECILL-B"
maintainers = [{ name = "Matthieu Gallet", email = "github@19pouces.net" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Natural Language :: English",
    "Natural Language :: French",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3",
]

[project.urls]
Repository = "https://github.com/d9pouces/hairgap"
Documentation = "https://github.com/d9pouces/hairgap"

[project.scripts]
pyhairgap = "hairgap.cli:main"

[dependency-groups]
dev = [
    "coverage>=6.0.1",
    "pytest>=8.0.0",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["hairgap"]
module-root = ""
