[tox:tox]
envlist = py,{py39,py310,py311,py312,py313,py314},coverage
minversion = 3.4.0

[testenv:py]
commands =
    docker run --rm -v {env:PWD}:/src python:3.14 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
    docker run --rm -v {env:PWD}:/src python:3.13 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
    docker run --rm -v {env:PWD}:/src python:3.12 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
    docker run --rm -v {env:PWD}:/src python:3.11 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
    docker run --rm -v {env:PWD}:/src python:3.10 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
    docker run --rm -v {env:PWD}:/src python:3.9 /bin/sh -c 'pip install uv tox pytest pip hairgap-binaries --upgrade > /dev/null && cd /src && pytest'
allowlist_externals =
    docker

[testenv:{py39,py310,py311,py312,py313,py314}]
commands =
    python3 -m pytest -v -s
deps =
    hairgap-binaries
    pytest

[testenv:coverage]
commands =
    python3 -m coverage run --source='hairgap' -m pytest
    python3 -m coverage xml -o build/coverage.xml
    python3 -m coverage report -m
deps =
    coverage
    hairgap-binaries
    pytest
